codecov:
  require_ci_to_pass: true

comment:
  behavior: default
  layout: diff, flags, files
  require_changes: false

coverage:
  status:
    patch:
      default:
        paths:
          - packages
        target: 80.0
    project:
      default:
        branches:
          - main
        paths:
          - packages
        target: 80.0
        threshold: 1.0

slack_app: false
