codecov:
  require_ci_to_pass: true

comment:
  behavior: default
  layout: diff, flags, files
  require_base: false # default true
  require_changes: false
  require_head: true # default true

coverage:
  status:
    patch:
      default:
        paths:
          - packages
        target: 90.0
    project:
      default:
        paths:
          - packages
        target: 90.0
        threshold: 1.0

slack_app: false
