steps:
  - label: ":package: Install Dependencies"
    key: deps
    command: nix-shell --run "pnpm install"
    plugins:
      - cache#v0.6.0:
          manifest: pnpm-lock.yaml
          path: node_modules
          restore: pipeline
          save: file
          compression: tgz
    if: "!build.pull_request.draft"

  - wait

  - group: ":sleuth_or_spy: Static Analysis"
    key: static
    steps:
      - label: ":prettier: Prettier"
        commands:
          - nix-shell --run "pnpm install"
          - nix-shell --run "pnpm nx run-many -t format:check"
        plugins:
          - cache#v0.6.0:
              manifest: pnpm-lock.yaml
              path: node_modules
              restore: file
              compression: tgz

      - label: ":eslint: ESLint"
        commands:
          - nix-shell --run "pnpm install"
          - nix-shell --run "pnpm nx run-many -t lint"
        plugins:
          - cache#v0.6.0:
              manifest: pnpm-lock.yaml
              path: node_modules
              restore: file
              compression: tgz
    if: "!build.pull_request.draft"

  - group: ":lock_with_ink_pen: Security Audits"
    key: audits
    steps:
      - label: ":pnpm: NPM Audit"
        commands:
          - nix-shell --run "pnpm install"
          - nix-shell --run "pnpm audit --prod"
        plugins:
          - cache#v0.6.0:
              manifest: pnpm-lock.yaml
              path: node_modules
              restore: file
              compression: tgz
    if: "!build.pull_request.draft"

  - wait

  - group: ":test_tube: Tests"
    key: tests
    steps:
      - label: ":vitest: Unit Tests"
        commands:
          - nix-shell --run "pnpm install"
          - |
            if [[ "$BUILDKITE_BRANCH" == "main" ]]; then
              nix-shell --run "pnpm nx affected -t test --base=origin/main~1 --head=origin/main --parallel=5"
            else
              nix-shell --run "pnpm nx affected -t test --base=origin/main --head=HEAD --parallel=5"
            fi
          - curl -Os https://uploader.codecov.io/latest/linux/codecov; chmod +x codecov; ./codecov
        plugins:
          - cache#v0.6.0:
              manifest: pnpm-lock.yaml
              path: node_modules
              restore: file
              compression: tgz
        env:
          NODE_ENV: "test"
    if: "!build.pull_request.draft"
